# Makefile for New AWK (nawk) for TOPS-20 KCC-20
# Only the main target, plus install and clean, work.
# On a simple test (nawk -f ps:<accounts>acct.awk ps:<accounts>tty127.acct)
# the KCC version ran in 51 sec, and the PCC version in 82 sec, with 
# identical output.
# [12-Dec-87]

DESTDIR = unix:
CC = kcc
CP = copy
MV = rename
O = .rel
RM = delete
X = .exe

YFLAGS = -d

# Changes suffixes to remove .l and .y, so Yacc and Lex are not run
.SUFFIXES:

.SUFFIXES:	.exe .rel .c .h

# -Darray=arrayx to get around conflict with MACRO assembler array
# -Dpclose=fclose (TOPS-20 has no pipes, so pclose() will never be called)
# With short, get compiler table overflow (MAXNODE exceeded)
CFLAGS = -Darray=arrayx -Dpclose=fclose -Dshort=int -Dpopen=fopen

OFILES = b${O} main${O} parse${O} proctab${O} tran${O} lib${O} run${O} 

#SOURCE = awk.h awkg.y awklx.l b.c main.c maketab.c parse.c lib.c run.c tran.c
SOURCE = awk.h awkg.c awklx.c b.c main.c maketab.c parse.c lib.c run.c tran.c

nawk${X}:	awkg${O} awklx${O} ${OFILES} ${ALLOC} awk.h
	${CC} ${CFLAGS} awkg${O} awklx${O} ${OFILES} ${ALLOC} -o nawk${X}

${OFILES} awklx${O}:	awk.h prevytab.h 

awkg${O}:	awk.h

ytab.h:	awkg${O}

prevytab.h:	ytab.h
#	-cmp -s ytab.h prevytab.h || (cp ytab.h prevytab.h; echo change maketab)
	${CP} ytab.h prevytab.h

proctab.c:	maketab
	maketab >proctab.c

# Compile proctab into proctab and procta (so later LINK from CC will find it)
proctab${O}:	proctab.c
	${CP} proctab.c procta.c
	${CC} ${CFLAGS} -c procta.c
	${CP} procta${O} proctab${O}

maketab:	prevytab.h maketab.c
	${CP} maketab.c maketb.c
	echo === Ignore missing lookup: it is not used ====
	${CC} maketb.c -o maketb
	reset
	${MV} maketb.* maketab.*

prcan:	NEW ${SOURCE} makefile
	@prcan $?
	@touch prcan

bundle:
	@bundle NEW ${SOURCE} makefile awk.1 compat.awk

backup:	${SOURCE} makefile NEW
	push panther $? awk
	touch backup

bowell:	${SOURCE} makefile NEW
	push bowell $? /usr/src/cmd/awk
	touch bowell

profile:
	make 'CFLAGS=-p'

lcomp:
	make 'CC=lcomp' 'CFLAGS='

lprint:
	echo 1>&2 "piping into can"
	@lprint -P "pr -l90 -w120" | can -fCW.8 -l90

clean:
	${RM} nawk${X}\n\
	${RM} *${O}.*\n\
	${RM} t.*.*\n\
	${RM} *temp*.*\n\
	${RM} *junk*.*
#	${RM} ytab.*.*
#	${RM} prevytab.h.*
#	${RM} maketab.*
#	${RM} proctab.c.*

install:	nawk${X}
	${CP} nawk$(X) ${DESTDIR}
